import { ModeToggle } from "@/components/mode-toggle";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ReactNode } from "react";

import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

type RootLayoutProps = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            <header className="bg-white dark:bg-gray-800 shadow-md">
              <nav className="container mx-auto p-4 flex justify-between items-center">
                <div className="text-2xl font-bold">MARADOCA</div>
                <ul className="flex space-x-4">
                  <li>
                    <a href="/" className="hover:text-blue-500">
                      Home
                    </a>
                  </li>
                  <li>
                    <a href="/music" className="hover:text-blue-500">
                      Music
                    </a>
                  </li>
                  <li>
                    <a href="/events" className="hover:text-blue-500">
                      Events
                    </a>
                  </li>
                  <li>
                    <a href="/about" className="hover:text-blue-500">
                      About
                    </a>
                  </li>
                  <li>
                    <a href="/contact" className="hover:text-blue-500">
                      Contact
                    </a>
                  </li>
                </ul>
                <ModeToggle />
              </nav>
            </header>
            <main className="flex-grow">{children}</main>
            <footer className="bg-white dark:bg-gray-800 shadow-md mt-8">
              <div className="container mx-auto p-4 text-center">
                <p>&copy; 2024 MARADOCA. All rights reserved.</p>
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
